# services:
#     db:
#     container_name: demomysql
#     image: 'mysql:5.7'
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     ports:
#     - 3336:3306
#     environment:
#       MYSQL_ROOT_PASSWORD: 1234
#       MYSQL_DATABASE: usersdb
#       MYSQL_USER: root
#       MYSQL_PASSWORD: 1234
#     volumes:
#     - docker/database:/var/lib/mysql
#     web:
#         build:
#           context: .
#           dockerfile: Dockerfile

version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'usersdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: